baseurl         = "/"
theme           = "casper-two"
languageCode    = "it"
#disqusShortname = "made-by-human-race"
paginate        = 6
#SectionPagesMenu = "main"

[outputFormats.Algolia]
  baseName = "algolia"
  isPlainText = true
  mediaType = "application/json"
  notAlternative = true

  [params.algolia]
  vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
  params = ["categories", "tags"]

[outputs]
  home = ["HTML", "RSS", "Algolia"]

[params]
  title       = "Made By Human Race"
  subtitle    = ""

  cover       = "/images/generic/head_aug20.png"
  description = ""
  metaDescription = ""
  googleAnalytics = "UA-41139230-12"
  customCSS = []
  RSSLink = ""

  twitterName = "madebyhumanrace"
  fbName = ""
  githubName = ""

  logo = ""
  orgName = "MBHR"
  orgWebsite = ""
  orgDescription = ""

  author = "MBHR"
  authorAvatar = "images/generic/avatar_220.png"
  authorLocation = "planer, Earth"
  authorWebsite = ""
  authorDescription = ""

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

  talkyardServerUrl = "https://comments-for-madebyhumanrace-org.talkyard.net"


[permalinks]
  post = "/:year/:month/:slug/"

[[menu.main]]
  name = "Casa"
  url = "/"
  weight = 400

[[menu.main]]
  name = "Oggetto/Soggetto/19"
  url = "/series/Oggetto Soggetto 19/"
  weight = 300

[[menu.main]]
  name = "Fotografi"
  url = "/categories/fotografi/"
  weight = 300

  [[menu.main]]
    name = "Diario"
    url = "/categories/diario/"
    weight = 200

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
